version: '3'
networks:
  backend:
    driver: bridge
volumes:
  mysql_data:
    driver: local
services:
  npm:
    build:
      context: ./npm
    volumes:
      - ../theme-fitspa/app:/var/www/html/app/template/default
      - ../theme-fitspa/html:/var/www/html/html/template/default
    networks:
      - backend
  apache:
    image: tabenguyen/eccube4-apache:1.5
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ../theme-fitspa/app:/var/www/html/app/template/default
      - ../theme-fitspa/html:/var/www/html/html/template/default
    networks:
      - backend
    depends_on:
      - "db"
  db:
    image: mysql:5.7
    command: mysqld --user=root
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/eccube4.sql:/docker-entrypoint-initdb.d/eccube4.sql
    environment:
      - MYSQL_DATABASE=eccube4
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=eccube4
      - MYSQL_PASSWORD=eccube4
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8082:80"
    depends_on:
      - "db"
    networks:
      - backend